-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 05:01:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema novitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema novitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `novitas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `novitas` ;

-- -----------------------------------------------------
-- Table `novitas`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novitas`.`skills` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `cost` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `tree` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 163
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `novitas`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novitas`.`user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `admin` TINYINT(0) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `novitas`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novitas`.`characters` (
  `character_id` INT NOT NULL AUTO_INCREMENT,
  `character_name` VARCHAR(45) NOT NULL,
  `level` TINYINT(0) NULL,
  `race` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `player` VARCHAR(45) NULL,
  `saved_skill_points` TINYINT(0) NULL,
  `saved_xp` TINYINT(0) NULL,
  PRIMARY KEY (`character_id`),
  CONSTRAINT `fk_characters_user`
    FOREIGN KEY (`character_id`)
    REFERENCES `novitas`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `novitas`.`characters_has_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novitas`.`characters_has_skills` (
  `characters_character_id` INT NOT NULL,
  `skills_id` INT(11) NOT NULL,
  `resource_amount` INT NULL,
  PRIMARY KEY (`characters_character_id`, `skills_id`),
  INDEX `fk_characters_has_skills_skills1_idx` (`skills_id` ASC) VISIBLE,
  INDEX `fk_characters_has_skills_characters1_idx` (`characters_character_id` ASC) VISIBLE,
  CONSTRAINT `fk_characters_has_skills_characters1`
    FOREIGN KEY (`characters_character_id`)
    REFERENCES `novitas`.`characters` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_has_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `novitas`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
